[package]
name = "borrower-registry"
version = "0.1.0"
description = "Borrower management program for CRE-Debt-Solana"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]
name = "borrower_registry"

[features]
no-entrypoint = []
no-idl = []
no-log-ix-name = []
cpi = ["no-entrypoint"]
default = []

[dependencies]
anchor-lang = "0.28.0"
